language: node_js
node_js:
  - node
  - lts/*
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "8.10.0"
install:
  - npm install
  - npm install graphql@${GRAPHQL_VERSION}
before_script:
  - npm run lint
  - npm run typescript

env:
  - GRAPHQL_VERSION=14.3.1
